Add-WindowsFeature AD-Domain-Services
Add-WindowsFeature AD-Certificate
Add-WindowsFeature ADCS-Cert-Authority
Add-WindowsFeature ADFS-Federation
Add-WindowsFeature ADRMS
Add-WindowsFeature DHCP
Add-WindowsFeature DNS
Add-WindowsFeature Fax
Add-WindowsFeature GPMC
Add-WindowsFeature WDS-Deployment
Add-WindowsFeature WDS-Transport
#Windows Update Server
Add-WindowsFeature UpdateServices
Add-WindowsFeature UpdateServices-WidDB
#Print Server
Add-WindowsFeature Print-Services
Add-WindowsFeature Print-Server
Add-WindowsFeature Print-Internet
Add-WindowsFeature Print-LPD-Service